export * from './src/box-config';
export * from './src/camera-config';
export * from './src/camera-folder-config';
export * from './src/capsule-config';
export * from './src/general-config';
export * from './src/physics-config';
export * from './src/physics-folder-config';
export * from './src/sphere-config';
export * from './src/wall-config';
